
language: python
python  : "2.7"
services:

install:
  - pip install .

script:
  - pip install nose coverage codecov pytest
  - pytest tests/

notifications:
  email:
    recipients:
      - andre@merzky.net
    on_success: change
    on_failure: always

after_success:
  - codecov

